DATASET:
    NAME: DeeplenstronomyDataset
    PARAMETERS:
        SIZE: 100
        OUTDIR: SimulationResults
        SEED: 6

COSMOLOGY:
    PARAMETERS:
        H0: 73.8 
        Om0: 0.3 
                 
IMAGE:
    PARAMETERS:
        exposure_time: 5400.
        numPix: 64
        pixel_scale: 0.08
        psf_type: 'PIXEL'
        read_noise: 4
        ccd_gain: 2.5
        
SURVEY:
    PARAMETERS:
        BANDS: g
        seeing: 0
        magnitude_zero_point: 25.9463
        sky_brightness: 22.0
        num_exposures: 1
        
SPECIES:
    GALAXY_1:
        NAME: LENS
        LIGHT_PROFILE_1:
            NAME: SERSIC_ELLIPSE
            PARAMETERS:
                magnitude: 19.5
                center_x: 0.0
                center_y: 0.0
                R_sersic: 10
                n_sersic: 4
                e1: 0.2
                e2: -0.1
        MASS_PROFILE_1:
            NAME: SIE 
            PARAMETERS:
                theta_E: 1.0
                e1: 0.1
                e2: -0.1
                center_x: 0.0
                center_y: 0.0
    GALAXY_2:
        NAME: SOURCE
        LIGHT_PROFILE_1:
            NAME: SERSIC_ELLIPSE
            PARAMETERS:
                magnitude: 21.5
                center_x: 0.0
                center_y: 0.0
                R_sersic: 
                    DISTRIBUTION:
                        NAME: uniform
                        PARAMETERS:
                            minimum: 0
                            maximum: 50
                n_sersic:
                    DISTRIBUTION:
                        NAME: uniform
                        PARAMETERS:
                            minimum: 0.5
                            maximum: 10
                e1: 
                    DISTRIBUTION:
                        NAME: uniform
                        PARAMETERS:
                            minimum: -1
                            maximum: 1
                e2:
                    DISTRIBUTION:
                        NAME: uniform
                        PARAMETERS:
                            minimum: -1
                            maximum: 1
    NOISE_1:
        NAME: POISSON_NOISE
        PARAMETERS:
            mean:
                DISTRIBUTION:
                    NAME: uniform
                    PARAMETERS:
                        minimum: 0
                        maximum: 2.0


GEOMETRY:
    CONFIGURATION_1:
        NAME: GALAXY_NOISELESS
        FRACTION: 1
        PLANE_1:
            OBJECT_1: LENS
            PARAMETERS:
                REDSHIFT: 0.2
        PLANE_2:
            OBJECT_1: SOURCE
            PARAMETERS:
                REDSHIFT: 0.7
        NOISE_SOURCE_1: POISSON_NOISE
